{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterRole }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "sshpiper.fullname" . }}
  labels:
    {{- include "sshpiper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.clusterRole }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "sshpiper.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sshpiper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
