{{- if .Values.rbac.create }}
{{- if and .Values.sshpiper.kubernetes_all_namespaces (not .Values.rbac.clusterRole) }}
{{- fail "sshpiper watches all namespaces, but rbac.clusterRole not enabled" }}
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterRole }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  name: {{ include "sshpiper.fullname" . }}
  labels:
    {{- include "sshpiper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - sshpiper.com
  resources:
  - pipes
  verbs:
  - get
  - list
  - watch
{{- end }}
