apiVersion: v1
kind: Service
metadata:
  name: {{ include "sshpiper.fullname" . }}
  labels:
    {{- include "sshpiper.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2222
      protocol: TCP
      name: sshpiper
  selector:
    {{- include "sshpiper.selectorLabels" . | nindent 4 }}
