# Default values for sshpiper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

sshpiper:
  loglevel: "info"
  ssh_host_key: "" # This is the private key of the ssh server. It is generated if not set.

image:
  repository: farmer1992/sshpiperd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 2222